name: ML Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python requirements.txt
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Download Data
      run: |
        mkdir -p data/raw
        curl -o data/raw/iris.csv https://example.com/data.csv
    - name: Train Model
      run: |
        python src/models/model1/train.py
    - name: Evaluate Model
      run: |
        python src/visualization/evaluation.py
    - name: Save Model
      run: |
        python src/models/model1/save_model.py

